Y3-S1-Projects/skilly-skill-sharing-and-learning-platform

backend/skilly/pom.xml, backend/skilly/src/main/java/com/example/skilly/Config/SecurityConfig.java, backend/skilly/src/main/java/com/example/skilly/Config/WebConfig.java, backend/skilly/src/main/java/com/example/skilly/Controllers/UserController.java, backend/skilly/src/main/java/com/example/skilly/Models/Post.java, backend/skilly/src/main/java/com/example/skilly/Models/User.java, backend/skilly/src/main/java/com/example/skilly/Repositories/SkillPostRepository.java, backend/skilly/src/main/java/com/example/skilly/Repositories/UserRepository.java, backend/skilly/src/main/java/com/example/skilly/Services/UserService.java, backend/skilly/src/main/java/com/example/skilly/SkillyApplication.java, frontend/package-lock.json, frontend/package.json, frontend/src/App.css, frontend/src/Pages/UserProfile.jsx
Mongodb database connected and added a user model with REST apis
=> setup : backend and database

backend/skilly/src/main/java/com/example/skilly/Config/SecurityHeadersFilter.java, backend/skilly/src/main/java/com/example/skilly/Config/WebConfig.java, backend/skilly/src/main/java/com/example/skilly/Models/Post.java, backend/skilly/src/main/java/com/example/skilly/Models/User.java, backend/skilly/src/main/java/com/example/skilly/Repositories/PostRepository.java, backend/skilly/src/main/java/com/example/skilly/Services/PostService.java, frontend/package-lock.json, frontend/package.json, frontend/src/Pages/Login.jsx
added login and created models
=> setup : backend

backend/skilly/pom.xml, backend/skilly/src/main/java/com/example/skilly/Config/SecurityConfig.java, backend/skilly/src/main/java/com/example/skilly/Controllers/AuthController.java, backend/skilly/src/main/java/com/example/skilly/Models/User.java, backend/skilly/src/main/java/com/example/skilly/Services/CustomOAuth2UserService.java, backend/skilly/src/main/java/com/example/skilly/Services/JwtService.java, frontend/src/App.jsx, frontend/src/Pages/Auth.jsx, frontend/src/Pages/Login.jsx
setup the basic steps of google login
=> setup : user login with google

.gitignore, backend/skilly/.gitignore, backend/skilly/src/main/java/com/example/skilly/Config/SecurityConfig.java, backend/skilly/src/main/java/com/example/skilly/Controllers/AuthController.java, backend/skilly/src/main/java/com/example/skilly/Controllers/UserController.java, backend/skilly/src/main/java/com/example/skilly/DTOs/LoginRequest.java, backend/skilly/src/main/java/com/example/skilly/Exceptions/ResourceNotFoundException.java, backend/skilly/src/main/java/com/example/skilly/Models/User.java, backend/skilly/src/main/java/com/example/skilly/Payload/MessageResponse.java, backend/skilly/src/main/java/com/example/skilly/Repositories/UserRepository.java, backend/skilly/src/main/java/com/example/skilly/Services/JwtService.java, backend/skilly/src/main/java/com/example/skilly/Services/UserService.java, frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/Pages/Login.jsx, frontend/src/Pages/Profile.jsx, frontend/src/Pages/Register.jsx, frontend/src/util/auth.js
Added user authentication with JWT-based login and registration. Implemented error handling for invalid inputs, duplicate emails, and incorrect credentials. Passwords are hashed before storing in the database.
=> feat : implement user registration and login

frontend/src/Pages/Profile.jsx
Fixed the error "userId not found"
=> fix:userId not found

backend/skilly/pom.xml, backend/skilly/src/main/java/com/example/skilly/Controllers/AuthController.java, backend/skilly/src/main/java/com/example/skilly/DTOs/GithubTokenRequest.java, frontend/src/App.jsx, frontend/src/Components/GithubCallback.jsx, frontend/src/Pages/Login.jsx
=> feat:githublogin

backend/skilly/src/main/java/com/example/skilly/Controllers/AuthController.java, backend/skilly/src/main/java/com/example/skilly/Controllers/UserController.java, backend/skilly/src/main/java/com/example/skilly/Services/UserService.java, frontend/components.json, frontend/components/ui/alert.jsx, frontend/components/ui/button.jsx, frontend/components/ui/dialog.jsx, frontend/components/ui/input.jsx, frontend/components/ui/label.jsx, frontend/components/ui/select.jsx, frontend/components/ui/tabs.jsx, frontend/components/ui/textarea.jsx, frontend/jsconfig.json, frontend/lib/utils.js, frontend/package-lock.json, frontend/package.json, frontend/src/App.css, frontend/src/Components/GithubCallback.jsx, frontend/src/Components/Header.jsx, frontend/src/Components/Modals/CreatePost.jsx, frontend/src/Pages/Login.jsx, frontend/src/Pages/UserProfile.jsx, frontend/src/index.css, frontend/vite.config.js
changed the user profile and add the post creation modal
=> refactor:user profile changed

backend/skilly/src/main/java/com/example/skilly/Config/SecurityConfig.java, backend/skilly/src/main/java/com/example/skilly/Config/WebConfig.java, backend/skilly/src/main/java/com/example/skilly/Controllers/AuthController.java, backend/skilly/src/main/java/com/example/skilly/Controllers/PostController.java, backend/skilly/src/main/java/com/example/skilly/Services/PostService.java, frontend/src/Pages/UserProfile.jsx
added post creation on profile and displays the user's posts on profile
=> setup:post creation

frontend/src/Components/Header.jsx, frontend/src/Pages/SocialFeed.jsx, frontend/src/Pages/UserProfile.jsx
added post likes and unlike feature
=> feat:like and unlike

backend/skilly/src/main/java/com/example/skilly/Controllers/PostController.java, backend/skilly/src/main/java/com/example/skilly/Controllers/SearchController.java, backend/skilly/src/main/java/com/example/skilly/Models/Post.java, backend/skilly/src/main/java/com/example/skilly/Repositories/PostRepository.java, backend/skilly/src/main/java/com/example/skilly/Repositories/UserRepository.java, backend/skilly/src/main/java/com/example/skilly/Services/SearchService.java, frontend/src/App.jsx, frontend/src/Components/Header.jsx, frontend/src/Components/SearchResults .jsx, frontend/src/Pages/UserProfile.jsx, frontend/src/hooks/useUser.js
=> feat:user and post search

backend/skilly/src/main/java/com/example/skilly/Controllers/PostController.java, backend/skilly/src/main/java/com/example/skilly/DTOs/CommentRequest.java, backend/skilly/src/main/java/com/example/skilly/Models/Comment.java, backend/skilly/src/main/java/com/example/skilly/Models/Post.java, backend/skilly/src/main/java/com/example/skilly/Services/PostService.java
- Created comment schema and model
- Added route to add comments via POST /comments
=> feat: add backend support for post comments

backend/skilly/src/main/java/com/example/skilly/Controllers/UserController.java, backend/skilly/src/main/java/com/example/skilly/Services/UserService.java, frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/Components/Header.jsx, frontend/src/Components/SearchResults .jsx, frontend/src/Pages/PublicProfile.jsx, frontend/src/Pages/UserProfile.jsx
-Now users can follow/unfollow other users
-Like other posts
=> feat:follow/unfollow users

frontend/package-lock.json, frontend/package.json, frontend/public/icons/DocsIcon.jsx, frontend/public/icons/EditIcon.jsx, frontend/public/icons/StarsIcon.jsx, frontend/src/Components/CreatePostCard.jsx, frontend/src/Components/Header.jsx, frontend/src/Components/Modals/CreatePost.jsx, frontend/src/Components/Post.jsx, frontend/src/Pages/PublicProfile.jsx, frontend/src/Pages/UserProfile.jsx, frontend/src/hooks/usePostAction.js
-Created two different components for userprofile and public profile.
-Moved frequently used code into centralized utility functions to reduce repetition and improve maintainability. 
-Adjusted imports accordingly.
=> refactor: Simplify user profile

backend/skilly/pom.xml, backend/skilly/src/main/java/com/example/skilly/Config/SocketIOConfig.java, backend/skilly/src/main/java/com/example/skilly/Controllers/NotificationController.java, backend/skilly/src/main/java/com/example/skilly/Controllers/PostController.java, backend/skilly/src/main/java/com/example/skilly/DTOs/LikeNotification.java, backend/skilly/src/main/java/com/example/skilly/Models/Notification.java, backend/skilly/src/main/java/com/example/skilly/Repositories/NotificationRepository.java, backend/skilly/src/main/java/com/example/skilly/Services/SocketIOService.java, frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/Components/Header.jsx, frontend/src/Components/NotificationSystem.jsx, frontend/src/Pages/PublicProfile.jsx, frontend/src/services/webSocketService.js
-Added basic server config of socket io
-Created Notifications for likes
-Updated Header for showing notifications
=> feat: set up Socket.IO for notifications

frontend/src/Pages/UserProfile.jsx
- Added edit button and  delete button with textarea to update comments
=> feat: add edit and delete functionality for comments

frontend/src/Pages/UserProfile.jsx
Reverts Y3-S1-Projects/skilly-skill-sharing-and-learning-platform#17
=> Revert "feat: add edit and delete functionality for comments"

frontend/src/Pages/UserProfile.jsx
Reverts Y3-S1-Projects/skilly-skill-sharing-and-learning-platform#18
=> Revert "Revert "feat: add edit and delete functionality for comments""

backend/skilly/src/main/java/com/example/skilly/Controllers/PostController.java, backend/skilly/src/main/java/com/example/skilly/Services/PostService.java, frontend/src/Pages/UserProfile.jsx
=> feat:update post

frontend/src/App.jsx, frontend/src/Components/LearningPlans/LearningPlanCard.jsx, frontend/src/Components/LearningPlans/LearningPlanForm.jsx, frontend/src/Components/LearningPlans/ShareLearningPlanModal.jsx, frontend/src/Pages/CreateLearningPlan.jsx, frontend/src/Pages/EditLearningPlan.jsx, frontend/src/Pages/LearningPlanDetail.jsx, frontend/src/Pages/LearningPlans.jsx, frontend/src/services/learningPlanService.js
Implement create, update, delete, functionalities for Learning Plan(frontend)
=> feat:update plan

frontend/src/App.jsx, frontend/src/Components/PostCard.jsx, frontend/src/Pages/UserProfile.jsx
-moved posts, comments fetch for another component
=> refactor:post feed in userprofile

frontend/src/Components/LearningPlans/LearningPlanForm.jsx
update interface of learning plan form
=> refactor:change interface

backend/skilly/src/main/java/com/example/skilly/Controllers/PostController.java, backend/skilly/src/main/java/com/example/skilly/Models/Post.java, backend/skilly/src/main/java/com/example/skilly/Services/PostService.java, frontend/src/Components/PostCard.jsx, frontend/src/Pages/UserProfile.jsx
- Added share button to each post
- Prevented users from sharing their own posts
- Displayed original post owner's name
=> feat: add share functionality for posts

backend/skilly/src/main/java/com/example/skilly/Controllers/NotificationController.java, backend/skilly/src/main/java/com/example/skilly/Controllers/PostController.java, backend/skilly/src/main/java/com/example/skilly/DTOs/CommentNotification.java, backend/skilly/src/main/java/com/example/skilly/Services/SocketIOService.java
-Now users will receive a notification when someone commented on their post
=> feat:notification for comments

backend/skilly/src/main/java/com/example/skilly/Config/SecurityConfig.java, backend/skilly/src/main/java/com/example/skilly/Config/SocketIOConfig.java, backend/skilly/src/main/java/com/example/skilly/Config/WebConfig.java, backend/skilly/src/main/java/com/example/skilly/Controllers/AuthController.java, backend/skilly/src/main/java/com/example/skilly/Services/CustomOAuth2UserService.java, frontend/src/App.jsx, frontend/src/Components/GithubCallback.jsx, frontend/src/Components/LoginSuccess.jsx, frontend/src/Pages/Auth.jsx, frontend/src/Pages/Login.jsx, frontend/src/util/auth.js
=> feat:github oauth

frontend/src/Pages/LearningPlans.jsx, package-lock.json
now all plans show only user all plans
=> refactore:all-plans

frontend/src/Pages/CreateLearningPlan.jsx, frontend/src/Pages/EditLearningPlan.jsx, frontend/src/Pages/LearningPlanDetail.jsx, frontend/src/Pages/LearningPlans.jsx
now,the users completed plans showing on there accounts like completed plans and summery
=> refactor: complete-plan

frontend/src/Pages/PublicProfile.jsx, frontend/src/Pages/UserProfile.jsx
-Removed some unused components and codes
=> refactor:user profile changes

frontend/src/Components/Header.jsx, frontend/src/Components/Modals/UserConnections.jsx, frontend/src/Components/PostCard.jsx, frontend/src/Components/UserJoinDate.jsx, frontend/src/Pages/Login.jsx, frontend/src/Pages/PublicProfile.jsx, frontend/src/Pages/SocialFeed.jsx, frontend/src/Pages/UserProfile.jsx
-Added a feed to users to see latest updates
-Added post types badge
-
=> Added a feed

frontend/components/custom/FloatingLabelInput.jsx, frontend/components/ui/sonner.jsx, frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/Pages/Login.jsx, frontend/src/Pages/Register.jsx, frontend/src/index.css, frontend/tailwind.config.js
-Redesign the login and signup page
=> refactor:login and signup

frontend/package-lock.json, frontend/src/Components/Modals/CreatePost.jsx
=> refactor: remove unused tabs

frontend/src/Components/Modals/CreatePost.jsx
=> style: change font color create post

frontend/src/Components/Modals/CreatePost.jsx
=> style: update tab size

frontend/src/Components/PostCard.jsx
resize post components for better layout
=> style: resize post components

frontend/src/App.jsx, frontend/src/Components/Modals/UserConnections.jsx, frontend/src/Components/NotificationSystem.jsx, frontend/src/Components/PostView.jsx
Users can click on the notification and go see the post
=> feat: notification view

frontend/src/Components/PostCard.jsx, frontend/src/Components/PostView.jsx
Handles missing user details by displaying 'Deleted User' in PostCard when user fetch fails. Adds authorization header to comment posting in PostView and fixes avatar display to use the logged-in user's profile picture and username in the comment form.
=> Improve user handling in PostCard and PostView

backend/skilly/src/main/java/com/example/skilly/Controllers/PostController.java, backend/skilly/src/main/java/com/example/skilly/Models/Post.java, backend/skilly/src/main/java/com/example/skilly/Models/PostType.java, backend/skilly/src/main/java/com/example/skilly/Services/PostService.java, frontend/components/custom/ToolTip.jsx, frontend/package-lock.json, frontend/package.json, frontend/src/Components/CustomNotification/NotificationContainer.jsx, frontend/src/Components/CustomNotification/NotificationItem.jsx, frontend/src/Components/CustomNotification/NotificationProvider.jsx, frontend/src/Components/PostCard.jsx, frontend/src/Components/PostView.jsx, frontend/src/Pages/CreatePostPage.jsx, frontend/src/Pages/UserProfile.jsx, frontend/src/hooks/useNotifications.js, frontend/src/main.jsx
Implemented post save/unsave functionality in backend and frontend, including a new PostType enum and updated Post model. Added a custom notification system with context, provider, and UI components, replacing alert-based feedback. Refactored CreatePostPage and PostCard to use notifications, updated post creation flow, and enhanced UserProfile with an activities tab. Also updated dependencies and integrated a reusable Tooltip component.
=> Add post save feature and custom notifications

frontend/src/Components/CustomNotification/NotificationItem.jsx, frontend/src/Components/PostCard.jsx, frontend/src/Pages/EditProfilePage.jsx
Revamps the EditProfilePage layout and styling for a more modern, user-friendly interface, including a sidebar for profile picture updates and a cleaner form section. Updates NotificationItem to use a white background for default notifications and adjusts border styling. Also clarifies the save notification title in PostCard.
=> Redesign EditProfilePage and update notification styles

frontend/src/App.jsx, frontend/src/Components/Header.jsx, frontend/src/Pages/Explore.jsx
Introduced a new Explore page for discovering posts and users, added its route in App.jsx, and updated the Header component to remove the Community tab. The Explore page includes search, filtering, and displays posts from other users with tags and author info.
=> Add Explore page and update navigation

frontend/src/Components/CustomNotification/NotificationContainer.jsx, frontend/src/Components/CustomNotification/NotificationItem.jsx, frontend/src/Components/CustomNotification/NotificationProvider.jsx, frontend/src/Components/PostCard.jsx, frontend/src/main.jsx
Refactors the custom notification system to improve stacking, hover behavior, and visual clarity, limiting visible notifications to three and enhancing color cues for different types. Updates PostCard component styles for a cleaner, more consistent look with stronger borders, improved button and dropdown appearance, and better color contrast. Also changes the default notification position to top-right.
=> Revamp notification UI and update PostCard styling

backend/skilly/src/main/java/com/example/skilly/Controllers/PostController.java, backend/skilly/src/main/java/com/example/skilly/Repositories/PostRepository.java, backend/skilly/src/main/java/com/example/skilly/Services/PostService.java, frontend/src/Components/PostCard.jsx, frontend/src/Pages/Explore.jsx, frontend/src/Pages/UserProfile.jsx
Implemented backend endpoints and service logic for trending, recent, and popular post filters based on engagement and recency. Updated Explore page to use these filters and refactored the post grid to use the PostCard component. Enhanced PostCard with improved layout, author info, tag display, and read time estimation.
=> Add trending, recent, and popular post filters
